Developer->Mohammad Hasan, Shuvo Nath & Me(Tuhin).
User have to install QT Software and SQLite Software first. Than open "OOP Final Project .zip" file. Than go to "TMS.pro" and open this. It will open in QT software. Than go to "mainwindow.cpp" and change "OOP_BUS.db" Database Path as like as your Database File in QT. Than copy full text from "case 21-case 194.txt" and Build QT project. In Build/Run time maybe you face an error like "undefined reference to 'MainWindow::on_pushButton_21_clicked()'". If you see this error than clicked the error line and project will move you a page. Than select " case 21: to case 94: " all lines and Past the copied line which is you already copied from "case 21-case 194.txt". Than Build/Run again our project and use it. If you face any problem than contact me in this mail "shaharabituhin@gmail.com" . Thank You.